baseurl = "https://hungry-mayer-629540.netlify.com"
title = "Alexey Sofronov"
theme = ["hugo-coder"]
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Alexey Sofronov"

[params]
    author = "Alexey Sofronov"
    info = "Development Team Leader"
    description = "Alexey Sofronov personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/logo.jpeg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"
    
    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/Sofrik"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
